### ISSUE TITLE
The version history in ILIAS is no longer displayed (ILIAS 7.18, OnlyOffice 7.2.1.34). Old entries have also disappeared. Does anyone else observe this?

### ISSUE THREAD

**Issue by laewald** [fluxapps/OnlyOffice#13]
The version history in ILIAS is no longer displayed (ILIAS 7.18, OnlyOffice 7.2.1.34). Old entries have also disappeared. Does anyone else observe this?

_Originally posted by @laewald in https://github.com/fluxapps/OnlyOffice/discussions/12_

**Comment by mstuder** [comment]
do you think this is a issue of the only office plugin? can you provide some additional informations? please reopen the issue - if you think this is a only office bug.
